export const letters = [
    {
      string: "a",
      label: "a",
      value: 97,
      scaledValue: "a",
    },
    {
      string: "b",
      label: "b",
      value: 98,
      scaledValue: "b",
    },
    {
      string: "c",
      label: "c",
      value: 99,
      scaledValue: "c",
    },
    {
      string: "d",
      label: "d",
      value: 100,
      scaledValue: "d",
    },
    {
      string: "e",
      label: "e",
      value: 101,
      scaledValue: "e",
    },
    {
      string: "f",
      label: "f",
      value: 102,
      scaledValue: "f",
    },
    {
      string: "g",
      label: "g",
      value: 103,
      scaledValue: "g",
    },
    {
      string: "h",
      label: "h",
      value: 104,
      scaledValue: "h",
    },
    {
      string: "i",
      label: "i",
      value: 105,
      scaledValue: "i",
    },
    {
      string: "j",
      label: "j",
      value: 106,
      scaledValue: "j",
    },
    {
      string: "k",
      label: "k",
      value: 107,
      scaledValue: "k",
    },
    {
      string: "l",
      label: "l",
      value: 108,
      scaledValue: "l",
    },
    {
      string: "m",
      label: "m",
      value: 109,
      scaledValue: "m",
    },
    {
      string: "n",
      label: "n",
      value: 110,
      scaledValue: "n",
    },
    {
      string: "o",
      label: "o",
      value: 111,
      scaledValue: "o",
    },
    {
      string: "p",
      label: "p",
      value: 112,
      scaledValue: "p",
    },
    {
      string: "q",
      label: "q",
      value: 113,
      scaledValue: "q",
    },
    {
      string: "r",
      label: "r",
      value: 114,
      scaledValue: "r",
    },
    {
      string: "s",
      label: "s",
      value: 115,
      scaledValue: "s",
    },
    {
      string: "t",
      label: "t",
      value: 116,
      scaledValue: "t",
    },
    {
      string: "u",
      label: "u",
      value: 117,
      scaledValue: "u",
    },
    {
      string: "v",
      label: "v",
      value: 118,
      scaledValue: "v",
    },
    {
      string: "w",
      label: "w",
      value: 119,
      scaledValue: "w",
    },
    {
      string: "x",
      label: "x",
      value: 120,
      scaledValue: "x",
    },
    {
      string: "y",
      label: "y",
      value: 121,
      scaledValue: "y",
    },
    {
      string: "z",
      label: "z",
      value: 122,
      scaledValue: "z",
    },
  ];